"""cria tabela valuations

Revision ID: 3541970fdbc3
Revises: 89d0d15fb996
Create Date: 2026-07-22 17:33:05.591103

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3541970fdbc3"
down_revision: Union[str, Sequence[str], None] = "89d0d15fb996"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "valuations",
        sa.Column("valuation_id", sa.String(length=36), nullable=False),
        sa.Column("internal_order_id", sa.String(length=36), nullable=False),
        sa.Column("method", sa.String(length=50), nullable=False),
        sa.Column("estimated_value", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("minimum_value", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("maximum_value", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("price_per_m2", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column(
            "reference_area_m2", sa.Numeric(precision=12, scale=2), nullable=False
        ),
        sa.Column("confidence_score", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("calculated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["internal_order_id"], ["orders.internal_order_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("valuation_id"),
    )
    op.create_index(
        op.f("ix_valuations_internal_order_id"),
        "valuations",
        ["internal_order_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_valuations_internal_order_id"), table_name="valuations")
    op.drop_table("valuations")
    # ### end Alembic commands ###
