"""cria tabela property_assets

Revision ID: 4f0be0101ba0
Revises: 9543ab576aaa
Create Date: 2026-07-24 15:36:32.682782

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4f0be0101ba0"
down_revision: Union[str, Sequence[str], None] = "9543ab576aaa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "property_assets",
        sa.Column("property_asset_id", sa.String(length=36), nullable=False),
        sa.Column("property_type", sa.String(length=50), nullable=False),
        sa.Column("city_ibge_code", sa.String(length=7), nullable=False),
        sa.Column("postal_code", sa.String(length=9), nullable=False),
        sa.Column("neighborhood", sa.String(length=100), nullable=False),
        sa.Column("street", sa.String(length=150), nullable=False),
        sa.Column("number", sa.String(length=20), nullable=False),
        sa.Column("private_area_m2", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("built_area_m2", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("land_area_m2", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("bedrooms", sa.Integer(), nullable=True),
        sa.Column("bathrooms", sa.Integer(), nullable=True),
        sa.Column("parking_spaces", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["city_ibge_code"], ["cities.city_ibge_code"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("property_asset_id"),
    )
    op.create_index(
        op.f("ix_property_assets_city_ibge_code"),
        "property_assets",
        ["city_ibge_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_property_assets_postal_code"),
        "property_assets",
        ["postal_code"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_property_assets_postal_code"), table_name="property_assets")
    op.drop_index(
        op.f("ix_property_assets_city_ibge_code"), table_name="property_assets"
    )
    op.drop_table("property_assets")
    # ### end Alembic commands ###
