"""cria tabela cities

Revision ID: 7a3b58ae0f46
Revises: de9dc8f1c477
Create Date: 2026-07-17 17:29:23.103035

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7a3b58ae0f46"
down_revision: Union[str, Sequence[str], None] = "de9dc8f1c477"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cities",
        sa.Column("city_ibge_code", sa.String(length=7), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("state", sa.String(length=2), nullable=False),
        sa.Column(
            "active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(city_ibge_code) = 7", name="ck_cities_ibge_code_length"
        ),
        sa.CheckConstraint("length(state) = 2", name="ck_cities_state_length"),
        sa.PrimaryKeyConstraint("city_ibge_code"),
        sa.UniqueConstraint("name", "state", name="uq_cities_name_state"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cities")
    # ### end Alembic commands ###
