"""cria tabela de historico de status

Revision ID: 89d0d15fb996
Revises: 9c1f4e2d8a70
Create Date: 2026-07-17 18:33:31.837370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89d0d15fb996'
down_revision: Union[str, Sequence[str], None] = '9c1f4e2d8a70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_status_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('internal_order_id', sa.String(length=36), nullable=False),
    sa.Column('previous_status', sa.String(length=50), nullable=False),
    sa.Column('new_status', sa.String(length=50), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['internal_order_id'], ['orders.internal_order_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_status_history_internal_order_id'), 'order_status_history', ['internal_order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_status_history_internal_order_id'), table_name='order_status_history')
    op.drop_table('order_status_history')
    # ### end Alembic commands ###
