"""cria historico de precos de avaliacao

Revision ID: c4b08b7cf4c5
Revises: f55aafc1d077
Create Date: 2026-07-23 09:20:40.097773

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c4b08b7cf4c5"
down_revision: Union[str, Sequence[str], None] = "f55aafc1d077"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "city_valuation_price_history",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("city_valuation_price_id", sa.Integer(), nullable=False),
        sa.Column("city_ibge_code", sa.String(length=7), nullable=False),
        sa.Column("property_type", sa.String(length=20), nullable=False),
        sa.Column(
            "previous_price_per_m2", sa.Numeric(precision=18, scale=2), nullable=False
        ),
        sa.Column(
            "new_price_per_m2", sa.Numeric(precision=18, scale=2), nullable=False
        ),
        sa.Column(
            "changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["city_valuation_price_id"],
            ["city_valuation_prices.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_city_valuation_price_history_city_ibge_code"),
        "city_valuation_price_history",
        ["city_ibge_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_city_valuation_price_history_city_valuation_price_id"),
        "city_valuation_price_history",
        ["city_valuation_price_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_city_valuation_price_history_city_valuation_price_id"),
        table_name="city_valuation_price_history",
    )
    op.drop_index(
        op.f("ix_city_valuation_price_history_city_ibge_code"),
        table_name="city_valuation_price_history",
    )
    op.drop_table("city_valuation_price_history")
    # ### end Alembic commands ###
