"""cria tabela city valuation prices

Revision ID: c4f5ea746445
Revises: 3541970fdbc3
Create Date: 2026-07-22 18:56:22.962955

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c4f5ea746445"
down_revision: Union[str, Sequence[str], None] = "3541970fdbc3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "city_valuation_prices",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("city_ibge_code", sa.String(length=7), nullable=False),
        sa.Column("property_type", sa.String(length=20), nullable=False),
        sa.Column("price_per_m2", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "price_per_m2 > 0", name="ck_city_valuation_prices_positive_price"
        ),
        sa.ForeignKeyConstraint(
            ["city_ibge_code"], ["cities.city_ibge_code"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "city_ibge_code",
            "property_type",
            name="uq_city_valuation_prices_city_property_type",
        ),
    )
    op.create_index(
        op.f("ix_city_valuation_prices_city_ibge_code"),
        "city_valuation_prices",
        ["city_ibge_code"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_city_valuation_prices_city_ibge_code"),
        table_name="city_valuation_prices",
    )
    op.drop_table("city_valuation_prices")
    # ### end Alembic commands ###
