"""cria tabela orders

Revision ID: de9dc8f1c477
Revises:
Create Date: 2026-07-17 16:48:09.425657

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "de9dc8f1c477"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orders",
        sa.Column("internal_order_id", sa.String(length=36), nullable=False),
        sa.Column("external_order_id", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("property_json", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("internal_order_id"),
    )
    op.create_index(
        op.f("ix_orders_external_order_id"),
        "orders",
        ["external_order_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_orders_external_order_id"), table_name="orders")
    op.drop_table("orders")
    # ### end Alembic commands ###
