"""cria tabela order refusals

Revision ID: e0e8e75d67eb
Revises: e6299c0bbfa8
Create Date: 2026-07-23 16:51:16.731187

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e0e8e75d67eb"
down_revision: Union[str, Sequence[str], None] = "e6299c0bbfa8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order_refusals",
        sa.Column("refusal_id", sa.String(length=36), nullable=False),
        sa.Column("internal_order_id", sa.String(length=36), nullable=False),
        sa.Column("reason_code", sa.String(length=50), nullable=False),
        sa.Column("message", sa.String(length=500), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column(
            "refused_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["internal_order_id"], ["orders.internal_order_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("refusal_id"),
    )
    op.create_index(
        op.f("ix_order_refusals_internal_order_id"),
        "order_refusals",
        ["internal_order_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_order_refusals_internal_order_id"), table_name="order_refusals"
    )
    op.drop_table("order_refusals")
    # ### end Alembic commands ###
