"""adiciona responsavel ao historico de precos

Revision ID: e6299c0bbfa8
Revises: c4b08b7cf4c5
Create Date: 2026-07-23 11:01:05.242484

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e6299c0bbfa8"
down_revision: Union[str, Sequence[str], None] = "c4b08b7cf4c5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "city_valuation_price_history",
        sa.Column(
            "changed_by",
            sa.String(length=100),
            server_default=sa.text("'system'"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("city_valuation_price_history", "changed_by")
    # ### end Alembic commands ###
